---
# Docker repository configuration
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_channel }}"
docker_apt_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_package: "docker-{{ docker_edition }}"

# Docker Compose download URL
docker_compose_url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"

# System service names
docker_service_name: "docker"
docker_socket_name: "docker.socket"

# Configuration file paths
docker_daemon_config_file: "/etc/docker/daemon.json"
docker_service_override_dir: "/etc/systemd/system/docker.service.d"
docker_service_override_file: "{{ docker_service_override_dir }}/override.conf"

# Swarm state file
swarm_info_file: "/opt/docker/swarm-info.json"