# Ansible Group Variables Generated by Terraform
# DO NOT EDIT MANUALLY - This file is auto-generated

---
# Infrastructure Configuration
deploy_environment: "${environment}"
cluster_name: "fluffy-system-${environment}"

# Network Configuration
bastion_public_ip: "${bastion_ip}"
primary_manager_ip: "${primary_manager_ip}"

# Cluster Sizing
manager_count: ${manager_count}
edge_count: ${edge_count}
worker_count: ${worker_count}

# Docker Configuration
docker_edition: ce
docker_channel: stable
docker_version: "24.0"
docker_compose_version: "2.21.0"

# Swarm Configuration
swarm_init_advertise_addr: "${primary_manager_ip}"
swarm_listen_addr: "0.0.0.0:2377"
swarm_data_path_port: 4789
swarm_cert_expiry: "2160h0m0s"

# Network Configuration
docker_networks:
  - name: traefik-public
    driver: overlay
    attachable: true
    scope: swarm

# Domain Configuration (update these for your domains)
base_domain: "example.com"
traefik_domain: "traefik.{{ base_domain }}"
grafana_domain: "grafana.{{ base_domain }}"
prometheus_domain: "prometheus.{{ base_domain }}"
alertmanager_domain: "alertmanager.{{ base_domain }}"

# SSL/TLS Configuration
acme_email: "admin@{{ base_domain }}"

# Security Configuration
enable_ufw: true
ssh_port: 22

# Backup Configuration
backup_retention_days: 30

# Resource Limits
default_memory_limit: "512M"
default_cpu_limit: "1.0"
default_memory_reservation: "256M"
default_cpu_reservation: "0.5"