# Ansible Inventory Generated by Terraform
# DO NOT EDIT MANUALLY - This file is auto-generated

[bastion]
bastion-host ansible_host=${bastion_ip} ansible_user=${ssh_user} ansible_python_interpreter=auto_silent

[managers]
%{ for i, name in manager_names ~}
${name} ansible_host=${manager_private_ips[i]} ansible_user=${ssh_user}
%{ endfor ~}

[workers]
%{ for i, name in worker_names ~}
${name} ansible_host=${worker_private_ips[i]} ansible_user=${ssh_user}
%{ endfor ~}

[edge]
%{ for i, name in edge_names ~}
${name} ansible_host=${edge_private_ips[i]} ansible_user=${ssh_user}
%{ endfor ~}

[swarm:children]
managers
workers
edge

[docker_nodes:children]
managers
workers
edge

[swarm:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i ${ssh_key_path} -W %h:%p -q ${ssh_user}@${bastion_ip}" -o StrictHostKeyChecking=no'
ansible_python_interpreter=auto_silent
docker_edition=ce
docker_channel=stable
docker_compose_version=2.21.0
swarm_init_advertise_addr=${manager_private_ips[0]}
swarm_token_dir=/opt/docker/swarm-tokens

[managers:vars]
swarm_role=manager

[workers:vars]
swarm_role=worker

[edge:vars]
swarm_role=worker
node_labels='["traefik.enable=true", "edge=true"]'