---
# Global variables for all hosts in the Docker Swarm cluster

# Environment configuration
deploy_environment: "{{ environment_name | default('production') }}"
cluster_name: "docker-swarm-{{ deploy_environment }}"

# Docker configuration
docker_edition: ce
docker_channel: stable
docker_version: "24.0"
docker_compose_version: "2.21.0"

# Swarm configuration
swarm_init_advertise_addr: "{{ ansible_default_ipv4.address }}"
swarm_listen_addr: "0.0.0.0:2377"
swarm_data_path_port: 4789
swarm_cert_expiry: "2160h0m0s"

# Network configuration
docker_networks:
  - name: traefik-public
    driver: overlay
    attachable: true
    scope: swarm

# Resource limits (default)
default_memory_limit: "512M"
default_cpu_limit: "1.0"
default_memory_reservation: "256M"
default_cpu_reservation: "0.5"

# Backup configuration
backup_retention_days: 30
backup_s3_bucket: "{{ s3_backup_bucket | default('') }}"
backup_s3_region: "{{ s3_backup_region | default('us-east-1') }}"

# Monitoring configuration
prometheus_retention: "15d"
prometheus_retention_size: "5GB"
grafana_plugins:
  - grafana-clock-panel
  - grafana-simple-json-datasource
  - grafana-piechart-panel

# Security configuration
enable_ufw: true
ssh_port: 22
allowed_ssh_users:
  - root

# Logging configuration
log_driver: "json-file"
log_max_size: "100m"
log_max_file: "3"

# Health check defaults
health_check_interval: "30s"
health_check_timeout: "10s"
health_check_retries: 3
health_check_start_period: "60s"

# Update configuration
update_parallelism: 1
update_delay: "10s"
update_failure_action: "rollback"
update_monitor: "60s"
update_max_failure_ratio: 0.3

# Domain configuration (override in environment-specific files)
base_domain: "example.com"
traefik_domain: "traefik.{{ base_domain }}"
grafana_domain: "grafana.{{ base_domain }}"
prometheus_domain: "prometheus.{{ base_domain }}"
alertmanager_domain: "alertmanager.{{ base_domain }}"

# SSL/TLS configuration
acme_email: "admin@{{ base_domain }}"
ssl_protocols:
  - "TLSv1.2"
  - "TLSv1.3"

# Resource monitoring thresholds
cpu_threshold_warning: 80
cpu_threshold_critical: 95
memory_threshold_warning: 85
memory_threshold_critical: 95
disk_threshold_warning: 80
disk_threshold_critical: 90

# Service timeouts
service_start_timeout: 300
service_stop_timeout: 120
service_restart_timeout: 180