---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisite packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
  notify:
    - restart docker

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'
    owner: root
    group: root

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add users to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user != "root"

- name: Start and enable Docker service
  systemd:
    name: "{{ docker_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes