name: Bump version and create release

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --only dev

    - name: Configure Git
      run: |
        git config --local user.email "API_Gateway_Service_Release@beep.boop"
        git config --local user.name "API_Gateway_Service_Release_Robot 🤖"

    - name: Bump version
      run: |
        poetry run cz bump --changelog --yes
        
    - name: Push changes
      run: |
        git push origin main
        git push origin --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}